apiVersion: v1
kind: Pod
metadata:
  name: db-app
  labels:
    name: db-app-pod
spec:
  containers:
    - name: postgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
      ports:
        - containerPort: 5432