apiVersion: v1
kind: Service
metadata:
  name: db-app
  labels:
    name: db-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 5432
      port: 5432
      nodePort: 35432
  selector:
    name: db-app-service