apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: redis-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 6379
      port: 6379
      nodePort: 36379
  selector:
    name: redis-app-pod