apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: voting-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30080
  selector:
    name: voting-app-pod